# ===============================
# Application
# ===============================
spring.application.name=inventory-management-system

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_management_system
spring.datasource.username=root
spring.datasource.password=Krishna@6622

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Server
# ===============================
server.port=8080